sudo: required

#os services são programas que o travis CI precisa ter para executar seu processo de integração contínua
services:
    - docker

#essa tag diz o que deve ocorrer antes da fase de testes do processo de CI
before_install:
    - docker build -f Dockerfile.dev -t pedroprado/react-app .

#tag que diz os comandos a serem executados na fase de testes
script:
    # originalmente, o npm run test espera uma entrada para executar os testes
    # -e CI=true força a execução apenas uma vez
    # e saída do "npm run test"
    - docker run -e CI=true pedroprado/react-app npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    #bucket = é o nome do disco onde está o app
    bucket_name: "elasticbeanstalk-us-east-2-702988789672"
    #default= é o mesmo nome que o "app"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
